name: ci

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    strategy:
      matrix:
        node-version: [10, 12, 14, 16]
        os: [macos-12, ubuntu-20.04, windows-latest]

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: |
          npm install --ignore-scripts

      - name: Check licenses
        run: |
          npm run license-checker

      - name: Run tests
        run: |
          npm run test:ci

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel: true
          flag-name: run-${{ matrix.node-version }}-${{ matrix.os }}

      - name: pack artifacts
        run: |
          npm pack

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.os}}-${{matrix.node-version}}
          path: "fastify-3.17.0-sp1.tgz"

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true

  automerge:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
